package com.sss.crm.settings.mapper;

import com.sss.crm.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    /**
     * 查询所有的字典类型
     * @return
     */
    List<DicType> selectDicType();

    /**
     * 根据code查询字典类型
     * @param code
     * @return
     */
    DicType selectDicTypeByCode(String code);

    /**
     * 保存新建的字典类型
     * @param dicType
     * @return
     */
    int insertDicType(DicType dicType);

    /**
     * 保存修改的字典类型
     * @param dicType
     * @return
     */
    int updateDicType(DicType dicType);

    /**
     * 根据code批量删除字典类型
     * @param code
     * @return
     */
    int deleteDicTypeByCodes(String[] code);
}