package com.sss.crm.settings.mapper;

import com.sss.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Mon Jun 29 15:48:33 CST 2020
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 查询所有的dicvalue
     * @return
     */
    List<DicValue> selectDicValueAll();

    /**
     * 根据TypeCode和Value查询字典值
     * @param dicValue
     * @return
     */
    DicValue selectDicValueByTypeCodeAndValue(DicValue dicValue);

    /**
     * 保存创建的字典值
     * @param dicValue
     * @return
     */
    int insertDicValue(DicValue dicValue);

    /**
     * 根据id查询字典值
     * @param id
     * @return
     */
    DicValue selectDicValueById(String id);

    /**
     * 保存修改的字典值
     * @param dicValue
     * @return
     */
    int updateDicValue(DicValue dicValue);

    /**
     * 根据id批量删除字典值
     * @param id
     * @return
     */
    int deleteDicValueByIds(String[] id);

    /**
     * 根据typeCode查询字典值
     * @param typeCode
     * @return
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);
}